dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}

# above for SimpleStorage contrac
# below added for FundMe contract

dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"

networks:
  rinkeby:
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    verify: True
    # 'Verify: True' means to publish the source code to the network
  development:
    verify: False
