dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}

# above for SimpleStorage contrac
# below added for FundMe contract

dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
